apiVersion: apps/v1
kind: Deployment
metadata: 
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: shiva9921/webapp
        ports:
        - containerPort: 8080
          name: webapp

