
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: webapp
spec:
  type: LoadBalancer
  ports:
  - name: "webapp-service"
    port: 8080
    targetPort: 8080
  
  selector:
    app: webapp
  